---
# tasks file for ansible-role-nginx-settings

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Get include statement for conf.d path from {{ nginx_config }}"
  ansible.builtin.shell:
    cmd: grep -i "*.conf" {{ nginx_config }}
  register: output
  changed_when: output.rc != 0

- name: "Set facts based on conf.d output"
  ansible.builtin.set_fact:
    nginx_conf_path: "/{{ output.stdout.rsplit('/', 1)[0].split('/', 1)[1] }}/"

- name: "Get a list of NGINX conf files, with the SSL declaration"
  ansible.builtin.shell:
    cmd: grep -lr -i "ssl_certificate" {{ nginx_conf_path }}
  register: output
  changed_when: output.rc != 0

- name: "Set facts based on list of matching NGINX conf files"
  ansible.builtin.set_fact:
    ssl_configs: ["{{ output.stdout_lines }}"]

- name: "Print returned information"
  ansible.builtin.debug:
    msg:
      - "{{ ssl_configs }}"
#      - "{{ nginx_conf_path }}"