---
# tasks file for ansible-role-nginx-settings

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

#- name: "Gather the package facts"
#  ansible.builtin.package_facts:
#    manager: auto
#  when: ansible_facts.packages is not defined

- name: "Include tasks from assert playbook"
  ansible.builtin.include_tasks: assert.yaml

- name: "Include tasks from lookup playbook"
  ansible.builtin.include_tasks: lookup.yaml

- name: "Include tasks from install playbook"
  ansible.builtin.include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

- name: "Include tasks from cert playbook"
  ansible.builtin.include_tasks: cert.yaml
  when:
    - cert is defined
    - cert | bool