---
# Site tasks file for ansible-role-nginx-settings

- name: "Test if site variables are set correctly"
  ansible.builtin.assert:
    that:
      #- site is defined
      #- site is bool
      - site_name is defined
      - site_name is string
      - proxy_host is defined
      - proxy_host is string
      - proxy_port is defined
      - proxy_port is string
      - proxy_protocol is defined
      - proxy_protocol is string
      - server_name is defined
      - server_name is string
    quiet: yes

- name: "Test if Certificate variables are set correctly"
  ansible.builtin.assert:
    that:
      - certificate_file is defined
      - certificate_file is string
      - certificate_key is defined
      - certificate_key is string
      - certificate_chain is defined
      - certificate_chain is string
    quiet: yes

- name: "Upload Certificates to {{ inventory_hostname }} for {{ site_name }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0640'
  with_items:
    - src: "{{ certificate_file }}"
      dest: "{{ certificate_dir }}/"
    - src: "{{ certificate_key }}"
      dest: "{{ private_dir }}/"

- name: "Check if Virtual Hosts Config exists for {{ site_name }}"
  ansible.builtin.stat:
    path: "{{ virtual_hosts_configs }}/{{ site_name }}.conf"
  register: result

- name: "Set facts about Virtual Hosts Config exists for {{ site_name }}"
  ansible.builtin.set_fact:
    site_config_exist: True
  when:
    - result.stat.exists
    - result.failed is false

- name: "Deploy Site Template for {{ site_name }}"
  ansible.builtin.template:
    src: site_ssl.j2
    dest: "{{ virtual_hosts_configs }}/{{ site_name }}.conf"
  when:
    - site_config_exist is not defined
  notify: "Restart NGINX HTTP Server Daemon"
